# Ordner Optionen
folder_options: ["Rot", "Schwarz", "Marsch", "Fliegend"]

instruments: [
  #01
  "Floete",
  #02
  "Oboe",
  #03
  "Klarinette",
  #04
  "Fagott",
  #05
  "Alt-Sax",
  #06
  "Tenor-Sax",
  #07
  "Bari-Sax",
  #08
  "Fluegelhorn",
  #09
  "Horn in f",
  #10
  "Horn in es",
  #11
  "Trompete",
  #12
  "Posaune in c",
  #13
  "Posaune in b",
  #14
  "Tenorhorn-Bariton",
  #15
  "Bass in c",
  #16
  "Bass andere",
  #17
  "E-Bass",
  #18
  "Gesang",
  #19
  "Schlagwerk",
  #20
  "Rest"
]